apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis

images:
- name: argoproj/argocd
  newName: argoproj/argocd
  newTag: v0.12.0-rc1
- name: argoproj/argocd-ui
  newName: argoproj/argocd-ui
  newTag: v0.12.0-rc1
