apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


images:
- name: argoproj/argocd
  newName: argoproj/argocd
  newTag: v1.3.0-rc4
- name: argoproj/argocd-ui
  newName: argoproj/argocd-ui
  newTag: v1.3.0-rc4
resources:
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis
